services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Etc/UTC
    ports:
      - "5055:5055"
    volumes:
      - /containers/overseerr/config:/app/config
      - /mnt/data/overseerr/data:/app/data
    restart: unless-stopped
    networks:
      immich_net:
        ipv4_address: 172.25.0.10

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    volumes:
      - /mnt/data/immich/photos:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
      DB_HOSTNAME: database
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    networks:
      immich_net:
        ipv4_address: 172.25.0.9

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    volumes:
      - model-cache:/cache
    restart: always
    networks:
      immich_net:
        ipv4_address: 172.25.0.12

  redis:
    image: valkey/valkey:8-bookworm
    container_name: immich_redis
    restart: always
    networks:
      immich_net:
        ipv4_address: 172.25.0.13

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - /mnt/data/immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    networks:
      immich_net:
        ipv4_address: 172.25.0.14

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token eyJhIjoiYzE0Y2UzZTNmZmU3OTMzZWIwNmZmMDk4OWUzODA2ZGUiLCJ0IjoiZWFkNTFiNWQtNzY2YS00YTA4LWE5MDQtNWM3YWM4NTlkYTExIiwicyI6Ill6SXlNVGt6WW1RdFpEUmtNUzAwTkRZMkxUazRaRFl0TWpOaU56QmlNVFppWkRBNCJ9
    volumes:
      - /containers/cloudflared/config/config.yml:/etc/cloudflared/config.yml
    restart: unless-stopped
    networks:
      immich_net:
        ipv4_address: 172.25.0.16

  actual-server:
    image: actualbudget/actual-server:latest
    container_name: actualbudget_server
    restart: unless-stopped
    ports:
      - "5006:5006"
    volumes:
      - /mnt/data/actual/data:/data
    pull_policy: always
    networks:
      immich_net:
        ipv4_address: 172.25.0.11

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9001:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /containers/portainer/data:/data
    restart: always
    networks:
      immich_net:
        ipv4_address: 172.25.0.15

  yugioh-app:
    image: ghcr.io/chappomann/yugioh:latest
    container_name: yugioh_collection
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./.env.production
    environment:
      - TZ=Etc/UTC
    volumes:
      - /mnt/data/yugioh/database:/app/data
      - /mnt/data/yugioh/images:/app/public/images
    networks:
      immich_net:
        ipv4_address: 172.25.0.17
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  immich_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  model-cache:
    driver: local
  yugioh_data:
    driver: local
