version: "3.8"

services:
  yugioh-app:
    build:
      context: .
      dockerfile: Dockerfile.yugioh
      args:
        - GIT_REPO=https://github.com/chappomann/yugioh.git
        - GIT_BRANCH=develop
    container_name: yugioh_collection
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env.production
      - TZ=Etc/UTC
    volumes:
      - /mnt/data/yugioh/database:/app/data
      - /mnt/data/yugioh/images:/app/public/images
      - /etc/localtime:/etc/localtime:ro
    networks:
      immich_net:
        ipv4_address: 172.25.0.17
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  yugioh_data:
    driver: local
